# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c6edb08ec883d0295c668abcd1638807ab4aec24409988d4efe6c37117d384a44427e3661e74cdf1ce8d2819f9e6452121f5ee5512a5727f59f7eb885a3c13b

test:
  secret_key_base: 5d37c61f945c6e3e902b4919232b8e863acb90c381b5f6982aa9e741064c39a3c9002fdbc25c6655f9b04bed3bf581b8369db2a4ebcdcb827936d1ff32180fb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
